config/routes.rb
Rails.application.routes.draw do
#get 'employees/index', to: 'employees#index'
#get 'employees/:id', to: 'employees#destroy'
get 'employees/profile', to: 'employees#profile'
#get 'employees/:id', to: 'employees#destroy'
resources :employees do
	resources :employee_details
end

get 'profile', to: 'employees#profile'

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :employee
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :employee_details
validates :name,:designation, presence: true
validates :name, uniqueness: true
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
  belongs_to :employee
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
	def create
		@employee = Employee.find(params[:employee_id])
    @employee_detail = @employee.employee_details.create(employee_detail_params)
    redirect_to employee_path(@employee)
  end
 
  private
    def employee_detail_params
      params.require(:employee_detail).permit(:address, :city, :pincode)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	layout "employee"
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	def index
		@employees = Employee.all
		@text= params[:comment]
	end

	def show
		@employee = Employee.find(params[:id])
	end
	def profile
		@employee = Employee.find(1)
	end
	def new
		@employee = Employee.new
	end

	def edit
		@employee =Employee.find(params[:id])
	end

	def create
		@employee = Employee.create(employee_params)
		if @employee.save
			redirect_to employees_path
		else
			flash.now[:error] = "Error: Could not save Employee!!!"
			render 'new'
		end
	end

	def update
		@employee =Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to @employee
		else
			render 'edit'
		end
	end

	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to employees_path
	end

	private
		def employee_params
			params.require(:employee).permit(:name,:designation,:salary)
		end

	private
     def record_not_found
      render plain: "Nahi milra yaar bhai ye wala employee", status: 404
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee1_helper.rb
module Employee1Helper
end

app/helpers/employee2_helper.rb
module Employee2Helper
end

app/helpers/employee_detail_helper.rb
module EmployeeDetailHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/_emp_addresses.html.erb
<table>
	<tr>
		<th>Address</th>
		<th>City</th>
		<th>Pincode</th>
	</tr>
	<% @employee.employee_details.each do |emp| %>
	<tr>
		<td><%= emp.address %></td>
		<td><%= emp.city %></td>
		<td><%= emp.pincode %></td>
	</tr>
	<% end %>
</table>

app/views/employees/_emp_details.html.erb
<table>
	<tr>
		<td>
			<p>
				<strong>Name:</strong>
			</p>
		</td>
		<td>
			<p><%= @employee.name %>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<p>
				<strong>Designation:</strong>
			</p>
		</td>
		<td>
			<p><%= @employee.designation %>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<p>
				<strong>Salary:</strong>
			</p>
		</td>
		<td>
			<p><%= @employee.salary %>
			</p>
		</td>
	</tr>
</table>

app/views/employees/_form.html.erb
<%= form_for @employee do |form| %>
  <p><%= abc %></p>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this employee from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <%= form.label :name %><br>
  <%= form.text_field :name %>
</p>

<p>
  <%= form.label :designation %><br>
  <%= form.text_field :designation %>
</p>

<p>
  <%= form.label :salary %><br>
  <%= form.text_field :salary %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

app/views/employees/_form_for_adding_address.html.erb
<%= form_with(model: [ @employee, @employee.employee_details.build ], local: true) do |form| %>
  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>
  <p>
    <%= form.label :city %><br>
    <%= form.text_area :city %>
  </p>
  <p>
    <%= form.label :pincode %><br>
    <%= form.text_area :pincode %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/employees/edit.html.erb
<% content_for :head do %>
  <title>Edit Employee</title>
<% end %>
<% @name="Sengar" %>
<h1>Edit Employee</h1>
<%= render 'form', abc: @name  %>
<h2>Add Address:</h2>
<%= render 'form_for_adding_address' %>
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<% content_for :head do %>
<title>Employee List</title>
<% end %>
<h1>Employee Model</h1>
<%= image_tag "emp1.gif",size: "647x485", alt: "Employees GIF" %>
<! -- <%= video_tag "abc.mp4",size: "647x485", controls: true %> 
<br>
<h3>Details of all the Employees</h3>
<table style="box-shadow: 1px 1px 15px 2px black;width: 80%">
  <tr>
    <th>Employee ID</th>
    <th>Name</th>
    <th>Designation</th>
    <th>Salary</th>
    <th colspan="3">Links</th>
  </tr>

  <% @employees.each do |emp| %>
  <tr>
    <td><%= emp.id %></td>
    <td><%= emp.name %></td>
    <td><%= emp.designation %></td>
    <td><%= emp.salary %></td>
    <td><%= link_to "Show", emp %></td>
    <td><%= link_to "Edit", edit_employee_path(emp) %></td>
    <td><%= link_to 'Destroy', employee_path(emp), method: :delete,data: { confirm: 'Are you sure?' } %></td>  
   <!-- <td><%= check_box("Employee", emp.id) %></td>
    <td>  <%= file_field(:user, :avatar) %></td>
    <td>  <%= radio_button("article", "category", "rails") %></td>
      <td><%= label(:employee, :sumit) %></td>
      <td><%= password_field(:login, :pass) %></td> -->
    </tr>
    <% end %>
</table>
<br>
<%= submit_tag "Publish this article" %>
<h2><%= link_to "New Employee", new_employee_path %></h2>
<!-- <%= label_tag(:chk, "Checked") %>  
<%= text_field_tag(:comment) %> -->
<p><%= @text %>

app/views/employees/new.html.erb
<% content_for :head do %>
  <title>New Employee</title>
<% end %>
<% @name="Sumit" %>
<% flash.each do |type, msg| %>
  <div style="color: red;font-size: 20px	">
    <%= msg %>
  </div>
<% end %>
<h1>New Employee</h1>
<%= render 'form', abc: @name%>
<%= link_to 'Back', employees_path %>

app/views/employees/profile.html.erb
<h2> Profile Page </h2>
<%= @employee.name %>

app/views/employees/show.html.erb
<% content_for :head do %>
<title>Show Employee</title>
<% end %>
<h2>Details :</h2>
<%= render 'emp_details' %>
<h2>Addresses :</h2>
<%= render 'emp_addresses' %>
<h2><%= link_to 'List', employees_path %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CVExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/employee.html.erb
<html>
  <head>
<%= stylesheet_link_tag "special" %>
  	<%= yield :head %>
  </head>
  <body>
  <%= yield %>
  </body>
</html>